# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget


def hello():
    print('hello')


class Ui_MainWindow(QWidget, object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        MainWindow.setMinimumSize(QtCore.QSize(400, 500))
        MainWindow.setMaximumSize(QtCore.QSize(400, 500))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        MainWindow.setStyleSheet("\n"
                                 "\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.output = QtWidgets.QLabel(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(10, 10, 380, 100))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.output.setFont(font)
        self.output.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.output.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing)
        self.output.setObjectName("output")
        self.n1 = QtWidgets.QPushButton(self.centralwidget)
        self.n1.setGeometry(QtCore.QRect(100, 210, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        self.n1.setFont(font)
        self.n1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.n1.setMouseTracking(True)
        self.n1.setStyleSheet("background-color: rgb(170, 255, 255);\n"
                              "border: none;\n"
                              "outline: none;")
        self.n1.setAutoDefault(False)
        self.n1.setFlat(False)
        self.n1.setObjectName("n1")
        self.n5 = QtWidgets.QPushButton(self.centralwidget)
        self.n5.setGeometry(QtCore.QRect(170, 280, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        self.n5.setFont(font)
        self.n5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.n5.setMouseTracking(True)
        self.n5.setStyleSheet("background-color: rgb(170, 255, 255);border: none;\n"
                              "outline: none;")
        self.n5.setAutoDefault(False)
        self.n5.setFlat(False)
        self.n5.setObjectName("n5")
        self.n2 = QtWidgets.QPushButton(self.centralwidget)
        self.n2.setGeometry(QtCore.QRect(170, 210, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        self.n2.setFont(font)
        self.n2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.n2.setMouseTracking(True)
        self.n2.setStyleSheet("background-color: rgb(170, 255, 255);\n"
                              "border: none;\n"
                              "outline: none;")
        self.n2.setAutoDefault(False)
        self.n2.setFlat(False)
        self.n2.setObjectName("n2")
        self.n4 = QtWidgets.QPushButton(self.centralwidget)
        self.n4.setGeometry(QtCore.QRect(100, 280, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        self.n4.setFont(font)
        self.n4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.n4.setMouseTracking(True)
        self.n4.setStyleSheet("background-color: rgb(170, 255, 255); border: none;\n"
                              "outline: none;")
        self.n4.setAutoDefault(False)
        self.n4.setFlat(False)
        self.n4.setObjectName("n4")
        self.n6 = QtWidgets.QPushButton(self.centralwidget)
        self.n6.setGeometry(QtCore.QRect(240, 280, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        self.n6.setFont(font)
        self.n6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.n6.setMouseTracking(True)
        self.n6.setStyleSheet("border: none;\n"
                              "outline: none;background-color: rgb(170, 255, 255);")
        self.n6.setAutoDefault(False)
        self.n6.setFlat(False)
        self.n6.setObjectName("n6")
        self.n3 = QtWidgets.QPushButton(self.centralwidget)
        self.n3.setGeometry(QtCore.QRect(240, 210, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        self.n3.setFont(font)
        self.n3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.n3.setMouseTracking(True)
        self.n3.setStyleSheet("background-color: rgb(170, 255, 255);\n"
                              "border: none;\n"
                              "outline: none;")
        self.n3.setAutoDefault(False)
        self.n3.setFlat(False)
        self.n3.setObjectName("n3")
        self.n8 = QtWidgets.QPushButton(self.centralwidget)
        self.n8.setGeometry(QtCore.QRect(170, 350, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        self.n8.setFont(font)
        self.n8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.n8.setMouseTracking(True)
        self.n8.setStyleSheet("border: none;\n"
                              "outline: none;background-color: rgb(170, 255, 255);")
        self.n8.setAutoDefault(False)
        self.n8.setFlat(False)
        self.n8.setObjectName("n8")
        self.n9 = QtWidgets.QPushButton(self.centralwidget)
        self.n9.setGeometry(QtCore.QRect(240, 350, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        self.n9.setFont(font)
        self.n9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.n9.setMouseTracking(True)
        self.n9.setStyleSheet("border: none;\n"
                              "outline: none;background-color: rgb(170, 255, 255);")
        self.n9.setAutoDefault(False)
        self.n9.setFlat(False)
        self.n9.setObjectName("n9")
        self.n7 = QtWidgets.QPushButton(self.centralwidget)
        self.n7.setGeometry(QtCore.QRect(100, 350, 60, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        self.n7.setFont(font)
        self.n7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.n7.setMouseTracking(True)
        self.n7.setStyleSheet("border: none;\n"
                              "outline: none;background-color: rgb(170, 255, 255);")
        self.n7.setAutoDefault(False)
        self.n7.setFlat(False)
        self.n7.setObjectName("n7")
        self.n0 = QtWidgets.QPushButton(self.centralwidget)
        self.n0.setGeometry(QtCore.QRect(100, 420, 200, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        self.n0.setFont(font)
        self.n0.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.n0.setMouseTracking(True)
        self.n0.setStyleSheet("border: none;\n"
                              "outline: none;background-color: rgb(170, 255, 127);")
        self.n0.setAutoDefault(False)
        self.n0.setFlat(False)
        self.n0.setObjectName("n0")

        self.sign = QtWidgets.QPushButton(self.centralwidget)
        self.sign.setGeometry(QtCore.QRect(310, 350, 80, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        self.sign.setFont(font)
        self.sign.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sign.setMouseTracking(True)
        self.sign.setStyleSheet("border: none;\n"
                                "outline: none;background-color: rgb(255, 170, 255);")
        self.sign.setAutoDefault(False)
        self.sign.setFlat(False)
        self.sign.setObjectName("+/-")

        self.equal = QtWidgets.QPushButton(self.centralwidget)
        self.equal.setGeometry(QtCore.QRect(310, 420, 80, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        self.equal.setFont(font)
        self.equal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.equal.setMouseTracking(True)
        self.equal.setStyleSheet("border: none;\n"
                                 "outline: none;background-color: rgb(255, 168, 105);")
        self.equal.setAutoDefault(False)
        self.equal.setFlat(False)
        self.equal.setObjectName("equal")
        self.plus = QtWidgets.QPushButton(self.centralwidget)
        self.plus.setGeometry(QtCore.QRect(310, 280, 80, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        self.plus.setFont(font)
        self.plus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.plus.setMouseTracking(True)
        self.plus.setStyleSheet("border: none;\n"
                                "outline: none;\n"
                                "background-color: rgb(255, 170, 255);")
        self.plus.setAutoDefault(False)
        self.plus.setFlat(False)
        self.plus.setObjectName("plus")
        self.minus = QtWidgets.QPushButton(self.centralwidget)
        self.minus.setGeometry(QtCore.QRect(310, 210, 80, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        self.minus.setFont(font)
        self.minus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minus.setMouseTracking(True)
        self.minus.setStyleSheet("border: none;\n"
                                 "outline: none;\n"
                                 "background-color: rgb(255, 170, 255);")
        self.minus.setAutoDefault(False)
        self.minus.setFlat(False)
        self.minus.setObjectName("minus")
        self.umnozh = QtWidgets.QPushButton(self.centralwidget)
        self.umnozh.setGeometry(QtCore.QRect(10, 210, 80, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        self.umnozh.setFont(font)
        self.umnozh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.umnozh.setMouseTracking(True)
        self.umnozh.setStyleSheet("border: none;\n"
                                  "outline: none;\n"
                                  "background-color: rgb(255, 170, 255);")
        self.umnozh.setAutoDefault(False)
        self.umnozh.setFlat(False)
        self.umnozh.setObjectName("umnozh")
        self.div_float = QtWidgets.QPushButton(self.centralwidget)
        self.div_float.setGeometry(QtCore.QRect(10, 280, 80, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        self.div_float.setFont(font)
        self.div_float.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.div_float.setMouseTracking(True)
        self.div_float.setStyleSheet("border: none;\n"
                                     "outline: none;\n"
                                     "background-color: rgb(255, 170, 255);")
        self.div_float.setAutoDefault(False)
        self.div_float.setFlat(False)
        self.div_float.setObjectName("div_float")
        self.pow = QtWidgets.QPushButton(self.centralwidget)
        self.pow.setGeometry(QtCore.QRect(10, 350, 80, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        self.pow.setFont(font)
        self.pow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pow.setMouseTracking(True)
        self.pow.setStyleSheet("border: none;\n"
                               "outline: none;\n"
                               "background-color: rgb(255, 170, 255);")
        self.pow.setAutoDefault(False)
        self.pow.setFlat(False)
        self.pow.setObjectName("pow")
        self.mod = QtWidgets.QPushButton(self.centralwidget)
        self.mod.setGeometry(QtCore.QRect(10, 420, 80, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        self.mod.setFont(font)
        self.mod.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mod.setMouseTracking(True)
        self.mod.setStyleSheet("border: none;\n"
                               "outline: none;\n"
                               "background-color: rgb(255, 170, 255);")
        self.mod.setAutoDefault(False)
        self.mod.setFlat(False)
        self.mod.setObjectName("mod")
        self.clear_all = QtWidgets.QPushButton(self.centralwidget)
        self.clear_all.setGeometry(QtCore.QRect(10, 140, 91, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        self.clear_all.setFont(font)
        self.clear_all.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clear_all.setMouseTracking(True)
        self.clear_all.setStyleSheet("border: none;\n"
                                     "background-color: rgb(255, 255, 127);\n"
                                     "outline: none;")
        self.clear_all.setAutoDefault(False)
        self.clear_all.setFlat(False)
        self.clear_all.setObjectName("clear_all")
        self.clear = QtWidgets.QPushButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(110, 140, 81, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        self.clear.setFont(font)
        self.clear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clear.setMouseTracking(True)
        self.clear.setStyleSheet("border: none;\n"
                                 "background-color: rgb(255, 255, 127);\n"
                                 "outline: none;")
        self.clear.setAutoDefault(False)
        self.clear.setFlat(False)
        self.clear.setObjectName("clear")
        self.convert_to = QtWidgets.QPushButton(self.centralwidget)
        self.convert_to.setGeometry(QtCore.QRect(200, 140, 91, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        self.convert_to.setFont(font)
        self.convert_to.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.convert_to.setMouseTracking(True)
        self.convert_to.setStyleSheet("border: none;\n"
                                      "background-color: rgb(255, 255, 127);\n"
                                      "outline: none;")
        self.convert_to.setAutoDefault(False)
        self.convert_to.setFlat(False)
        self.convert_to.setObjectName("convert_to")
        self.float = QtWidgets.QPushButton(self.centralwidget)
        self.float.setGeometry(QtCore.QRect(299, 140, 91, 60))
        font = QtGui.QFont()
        font.setFamily("Malgun Gothic Semilight")
        font.setPointSize(20)
        self.float.setFont(font)
        self.float.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.float.setMouseTracking(True)
        self.float.setStyleSheet("border: none;\n"
                                 "background-color: rgb(255, 255, 127);\n"
                                 "outline: none;")
        self.float.setAutoDefault(False)
        self.float.setFlat(False)
        self.float.setObjectName("float")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.output.setText(_translate("MainWindow", ""))
        self.n1.setText(_translate("MainWindow", "1"))
        self.n5.setText(_translate("MainWindow", "5"))
        self.n2.setText(_translate("MainWindow", "2"))
        self.n4.setText(_translate("MainWindow", "4"))
        self.n6.setText(_translate("MainWindow", "6"))
        self.n3.setText(_translate("MainWindow", "3"))
        self.n8.setText(_translate("MainWindow", "8"))
        self.n9.setText(_translate("MainWindow", "9"))
        self.n7.setText(_translate("MainWindow", "7"))
        self.n0.setText(_translate("MainWindow", "0"))
        self.equal.setText(_translate("MainWindow", "="))
        self.plus.setText(_translate("MainWindow", "+"))
        self.minus.setText(_translate("MainWindow", "-"))
        self.umnozh.setText(_translate("MainWindow", "*"))
        self.div_float.setText(_translate("MainWindow", "/"))
        self.pow.setText(_translate("MainWindow", "^"))
        self.mod.setText(_translate("MainWindow", "%"))
        self.clear_all.setText(_translate("MainWindow", "CA"))
        self.clear.setText(_translate("MainWindow", "C"))
        self.convert_to.setText(_translate("MainWindow", "->"))
        self.float.setText(_translate("MainWindow", ","))
        self.sign.setText(_translate("MainWindow", "+/-"))
